[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/knolleary/pubsubclient.git#v2.8
    https://github.com/bblanchon/ArduinoJson.git#v7.4.3
    https://github.com/dvarrel/ESPAsyncTCP.git#1.2.4
    https://github.com/lacamera/ESPAsyncWebServer.git#3.1.0
    https://github.com/ayushsharma82/ElegantOTA.git#4.0.0
    https://github.com/emelianov/modbus-esp8266.git#4.1.1

build_flags =
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1

lib_ignore =
    ESPAsyncWebServer
    ESPAsyncTCP-esphome
